// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: firms.sql

package db

import (
	"context"
)

const createFirm = `-- name: CreateFirm :one
INSERT INTO firms (id, created_at, updated_at, email, ustId, streetName, plz, hashed_password)
VALUES (
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, created_at, updated_at, email, ustid, streetname, plz, hashed_password
`

type CreateFirmParams struct {
	Email          string
	Ustid          string
	Streetname     string
	Plz            string
	HashedPassword string
}

func (q *Queries) CreateFirm(ctx context.Context, arg CreateFirmParams) (Firm, error) {
	row := q.db.QueryRowContext(ctx, createFirm,
		arg.Email,
		arg.Ustid,
		arg.Streetname,
		arg.Plz,
		arg.HashedPassword,
	)
	var i Firm
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Ustid,
		&i.Streetname,
		&i.Plz,
		&i.HashedPassword,
	)
	return i, err
}
