// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getEmail.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getByEmail = `-- name: GetByEmail :one
SELECT users.id, users.created_at, users.updated_at, name, is_admin, is_teamhead, users.hashed_password, users.email, firms.id, firms.created_at, firms.updated_at, firms.email, ustid, streetname, plz, firms.hashed_password FROM users
INNER JOIN firms
  ON users.email = firms.email AND users.hashed_password = firms.hashed_password
WHERE users.email = $1
`

type GetByEmailRow struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Name             string
	IsAdmin          bool
	IsTeamhead       bool
	HashedPassword   string
	Email            string
	ID_2             uuid.UUID
	CreatedAt_2      time.Time
	UpdatedAt_2      time.Time
	Email_2          string
	Ustid            string
	Streetname       string
	Plz              string
	HashedPassword_2 string
}

func (q *Queries) GetByEmail(ctx context.Context, email string) (GetByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getByEmail, email)
	var i GetByEmailRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.IsAdmin,
		&i.IsTeamhead,
		&i.HashedPassword,
		&i.Email,
		&i.ID_2,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.Email_2,
		&i.Ustid,
		&i.Streetname,
		&i.Plz,
		&i.HashedPassword_2,
	)
	return i, err
}
